# deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "flowise"
  labels:
    app: "flowise"
spec:
  selector:
    matchLabels:
      app: "flowise"
  replicas: 1
  template:
    metadata:
      labels:
        app: "flowise"
    spec:
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: flowise-pv-claim
      containers:
      - name: "flowise"
        image: "europe-west8-docker.pkg.dev/midika-flowise/flowise-repo/flowise:latest"
        imagePullPolicy: "Always"
        resources: 
          requests:
            cpu: "0.5"
            memory: "0.8Gi"
        volumeMounts:
            - mountPath: "/root/.flowise"
              name: storage-volume
        envFrom:
        - configMapRef:
            name: dotenv
        env:
        - name: FLOWISE_USERNAME
          valueFrom:
            secretKeyRef:
              name: flowise-secrets
              key: FLOWISE_USERNAME
        - name: FLOWISE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flowise-secrets
              key: FLOWISE_PASSWORD
